config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tweets, only: [:index, :new, :create]
  get 'validate_user', to: 'tweets#validate_user'

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
  def validate_user
    request_token = OAuth::RequestToken.new(consumer, session[:request_token], session[:request_token_secret])
    access_token = request_token.get_access_token(:oauth_verifier => params[:oauth_verifier])
    session[:access_token_key] = access_token.token
    session[:access_token_secret] = access_token.secret

    redirect_to tweets_path
  end


  def authenticate
    unless session[:access_token_key] && session[:access_token_secret]
      request_token = consumer.get_request_token(:oauth_callback => "http://localhost:3000/validate_user")
      session[:request_token] = request_token.token
      session[:request_token_secret] = request_token.secret

      redirect_to request_token.authorize_url
    end
  end

  def client
    Twitter::REST::Client.new(
      :consumer_key => ENV['CONSUMER_KEY'],
      :consumer_secret => ENV['CONSUMER_SECRET_KEY'],
      :access_token => session[:access_token_key],
      :access_token_secret => session[:access_token_secret]
    )
  end

  private

  def consumer
    OAuth::Consumer.new(ENV['CONSUMER_KEY'], ENV['CONSUMER_SECRET_KEY'], {
      :site => "https://api.twitter.com"
    })
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate, only: [:index, :new, :create]
  require 'will_paginate/array' 


  def index
    @tweets = client.user_timeline.paginate(:page => params[:page], :per_page => 5)
  end

  def new
  end

  def create
    client.update(params[:body])
    redirect_to tweets_path
    flash[:success] = "Created Tweet Successfully"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h2>All Tweets</h2>
<%= link_to "Create Tweet", new_tweet_path %>
<div>
  <table>
  	<thead>
  		<tr>
  			<th>S.No</th>
  			<th>Body</th>
  			<th>Time</th>
  		</tr>
  	</thead>
  	<tbody>
  		<%- @tweets.each_with_index do |tweet, index| %>
  			<tr>
  				<td><%= index + 1 %></td>
  				<td><%= tweet.text %></td>
  				<td><%= tweet.created_at %></td>
  			</tr>
  		<% end %>
  	</tbody>
  </table>
</div>

<%= will_paginate @tweets %>

app/views/tweets/new.html.erb
<h2>New Tweet</h2>

<div>
	<%= form_for :tweet, url: tweets_path do %>
		<div>
			<%= label_tag :tweet %>
		</div>
		<div>
			<%= text_area_tag :body, "", required: true %>
		</div>
		<br/>
		<div>
			<%= button_tag :submit %>
		</div>
	<% end %>

</div>